# Changes here will be overwritten by Copier
_commit: v7.0.0-3-g0db8a76
_src_path: gh:eccenca/cmem-plugin-template
author_mail: itsmerr17@gmail.com
author_name: Sai Ranga Reddy Nukala
github_page: ''
project_description: Data Sources for Retail Demand Forecast
project_slug: retail-data-sources
project_type: generic
pypi: true

